object VideoWnd: TVideoWnd
  Left = 0
  Top = 0
  BorderStyle = bsNone
  ClientHeight = 203
  ClientWidth = 390
  Color = clBlack
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  KeyPreview = True
  OldCreateOrder = False
  PopupMode = pmExplicit
  OnClick = FormClick
  PixelsPerInch = 96
  TextHeight = 13
end
